name: ci

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      main-branch-name: main
      working-directory: .
      pnpm-version: 8.10.0
      number-of-agents: 3
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      # @TODO uns affected again
      parallel-commands-on-agents: |
        pnpm exec nx run-many --target=lint --parallel=3
        pnpm exec nx run-many --target=e2e --parallel=3
        pnpm exec nx run-many --target=test --parallel=3 --ci --code-coverage
        pnpm exec nx run-many --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      working-directory: .
      pnpm-version: 8.10.0
      number-of-agents: 3
